version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world2.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Print the Message
          command: echo This is my circleci project v2.
      - add_ssh_keys:
         fingerprints:
           - "5c:68:c9:53:4c:66:81:ef:40:82:40:31:60:60:f8:ce"
      - run:
          name: SSH to instance
          command: sshpass -p "ijaz1986@" ssh -o StrictHostKeyChecking=no casanova@52.91.191.112
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: "Create landing folder for API doc output"
          command: mkdir -p /tmp/workspace/api/v2
