version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world2.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Print the Message
          command: echo This is my circleci project v2.
       - run:
          name: Fix ssh Could not resolve hostname
          command: ssh-keyscan ubuntu@52.90.159.235 >> ~/.ssh/known_hosts
          
      - add_ssh_keys:
         fingerprints:
           - "58:ed:89:52:ee:1a:95:ac:da:29:97:fc:11:32:92:90"
      - run:
          name: SSH to instance
          command: ssh -o StrictHostKeyChecking=no casanova@52.91.191.112
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: "Create landing folder for API doc output"
          command: mkdir -p /tmp/workspace/api/v2
