version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Print the Message
          command: echo This is my circleci project v2.
      - run:
          name: install sshpass
          command: sudo apt-get install sshpass
      - run:
          name: Fix ssh Could not resolve hostname
          command: ssh-keyscan ubuntu@52.90.159.235 >> ~/.ssh/known_hosts
      - add_ssh_keys:
         fingerprints:
           - "5c:68:c9:53:4c:66:81:ef:40:82:40:31:60:60:f8:ce"
      - run:
          name: SSH to instance
          command: sshpass -p "DDpropery@001" ssh -v -o StrictHostKeyChecking=no casanova@34.229.214.2
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: "Create landing folder for API doc output"
          command: mkdir -p /tmp/workspace/api/v2
